trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    pip install -r requirements.txt
    python -m unittest discover
  displayName: 'Install and Test'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your Azure Connection>'
    appType: 'webAppLinux'
    appName: '<Your App Name>'
    package: '.'
